### ISSUE TITLE
AttributeError: 'ExperimentRunDetail' object has no attribute 'notification_group'

### ISSUE THREAD

**Issue by sebastroy** [UbiOps/client-library-python#11]
When calling "to_dict" on ExperimentRunDetail I get the following error

AttributeError: 'ExperimentRunDetail' object has no attribute 'notification_group'

File "/usr/local/lib/python3.12/site-packages/ubiops/models/deployment_request_batch_detail.py", line 451, in to_dict	api
	value = getattr(self, attr)	api
	^^^^^^^^^^^^^^^^^^^	api
	AttributeError: 'ExperimentRunDetail' object has no attribute 'notification_group'

I ran into something similar for another class about 2 weeks ago but did not take notes as to how that happened.

version 4.3.0 for Ubuntu x86_64 platform (Docker build)

**Comment by sebastroy** [comment]
I get the same error with version 4.2.0

**Comment by Sascha-UbiOps** [comment]
My apologies for the delayed answer.

Thank you for reporting this issue. It will be fixed in the next release (4.5.0).

If you have more questions/feedback, would you please contact us at https://ubiops.com/support? Our usual response time is much faster via that link.
