### ISSUE TITLE
Incorporate progress bar for file uploads and downloads

### ISSUE THREAD

**Issue by Adesoji1** [UbiOps/client-library-python#8]
It appears that the ubiops.utils.upload_file function doesn't have a progress_callback argument. To track the progress of the file upload

```
from ubiops import utils

#Upload a file
file_uri = ubiops.utils.upload_file( 
  client = api_client, #a UbiOps API client 
  project_name = "my-project", 
  file_path = "file", 
  bucket_name = "your-bucket", 
  file_name = "files/file" 
)


```
@Sascha-UbiOps @ricardo-ubiops @elif-ubiops

**Comment by Sascha-UbiOps** [comment]
Hi,

The `ubiops.utils.upload_file` function already shows an upload progress bar by default. You can turn that off with the `_progress_bar=False` parameter.

Can you explain why you want to be able to configure the progress_callback yourself?

Kind regards,
Sascha
